server:
    port: 9090

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: <login>
    password: <password>
    properties:
      mail:
        smtp:
          ssl:
            enable: true
